var files_dup =
[
    [ "app_camerapipeline.c", "app__camerapipeline_8c.html", "app__camerapipeline_8c" ],
    [ "app_camerapipeline.h", "app__camerapipeline_8h.html", "app__camerapipeline_8h" ],
    [ "app_config.h", "app__config_8h.html", "app__config_8h" ],
    [ "common_deploy.py", "common__deploy_8py.html", "common__deploy_8py" ],
    [ "crop_img.c", "crop__img_8c.html", "crop__img_8c" ],
    [ "crop_img.h", "crop__img_8h.html", "crop__img_8h" ],
    [ "data_loader.py", "data__loader_8py.html", "data__loader_8py" ],
    [ "deploy.py", "deploy_8py.html", "deploy_8py" ],
    [ "display_keypoints_13.h", "display__keypoints__13_8h.html", "display__keypoints__13_8h" ],
    [ "display_keypoints_17.h", "display__keypoints__17_8h.html", "display__keypoints__17_8h" ],
    [ "display_mpe.c", "display__mpe_8c.html", "display__mpe_8c" ],
    [ "display_mpe.h", "display__mpe_8h.html", "display__mpe_8h" ],
    [ "display_spe.c", "display__spe_8c.html", "display__spe_8c" ],
    [ "display_spe.h", "display__spe_8h.html", "display__spe_8h" ],
    [ "evaluate.py", "evaluate_8py.html", "evaluate_8py" ],
    [ "external_memory_mgt.py", "external__memory__mgt_8py.html", "external__memory__mgt_8py" ],
    [ "gen_h_file.py", "gen__h__file_8py.html", "gen__h__file_8py" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "metrics.py", "metrics_8py.html", "metrics_8py" ],
    [ "models_mgt.py", "models__mgt_8py.html", "models__mgt_8py" ],
    [ "parse_config.py", "parse__config_8py.html", "parse__config_8py" ],
    [ "postprocess.py", "postprocess_8py.html", "postprocess_8py" ],
    [ "preprocess.py", "preprocess_8py.html", "preprocess_8py" ],
    [ "quantize.py", "quantize_8py.html", "quantize_8py" ],
    [ "stm32ai_main.py", "stm32ai__main_8py.html", "stm32ai__main_8py" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ]
];