STM32N6 NPU Deployment — Politecnico di Milano: app_camerapipeline.h File Reference
app_camerapipeline.h File Reference
Macros
#define SCREEN_HEIGHT (480)
#define SCREEN_WIDTH (800)
Functions
void CameraPipeline_Init (uint32_t *lcd_bg_width, uint32_t *lcd_bg_height, uint32_t *pitch_nn)
Init the camera and the 2 DCMIPP pipes.
void CameraPipeline_DeInit (void)
void CameraPipeline_Start (void)
void CameraPipeline_DisplayPipe_Start (uint8_t *display_pipe_dst, uint32_t cam_mode)
void CameraPipeline_DisplayPipe_Stop (void)
void CameraPipeline_NNPipe_Start (uint8_t *nn_pipe_dst, uint32_t cam_mode)
void CameraPipeline_IspUpdate (void)
Detailed Description
Author
GPM Application Team
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file app_camerapipeline.h.
Macro Definition Documentation
SCREEN_HEIGHT
#define SCREEN_HEIGHT (480)
Definition at line 21 of file app_camerapipeline.h.
SCREEN_WIDTH
#define SCREEN_WIDTH (800)
Definition at line 22 of file app_camerapipeline.h.
Function Documentation
CameraPipeline_DeInit()
void CameraPipeline_DeInit (void)
Definition at line 139 of file app_camerapipeline.c.
CameraPipeline_DisplayPipe_Start()
void CameraPipeline_DisplayPipe_Start (uint8_t * display_pipe_dst, uint32_t cam_mode)
Definition at line 146 of file app_camerapipeline.c.
Referenced by __attribute__().
CameraPipeline_DisplayPipe_Stop()
void CameraPipeline_DisplayPipe_Stop (void)
Definition at line 161 of file app_camerapipeline.c.
CameraPipeline_Init()
void CameraPipeline_Init (uint32_t * lcd_bg_width, uint32_t * lcd_bg_height, uint32_t * pitch_nn)
Init the camera and the 2 DCMIPP pipes.
Parameters
lcd_bg_width display width
lcd_bg_height display height
pitch_nn output pitch computed by the CMW
Definition at line 121 of file app_camerapipeline.c.
References CAMERA_FLIP, CAMERA_FPS, CAMERA_HEIGHT, CAMERA_WIDTH, DCMIPP_PipeInitDisplay(), and DCMIPP_PipeInitNn().
Referenced by __attribute__().
CameraPipeline_IspUpdate()
void CameraPipeline_IspUpdate (void)
Definition at line 168 of file app_camerapipeline.c.
Referenced by __attribute__().
CameraPipeline_NNPipe_Start()
void CameraPipeline_NNPipe_Start (uint8_t * nn_pipe_dst, uint32_t cam_mode)
Definition at line 153 of file app_camerapipeline.c.
Referenced by __attribute__().
CameraPipeline_Start()
void CameraPipeline_Start (void)