STM32N6 NPU Deployment — Politecnico di Milano: evaluate Namespace Reference
evaluate Namespace Reference
Functions
None evaluate (DictConfig cfg=None, tf.data.Dataset eval_ds=None, Optional[str] model_path_to_evaluate=None, Optional[str] name_ds='test_set')
Function Documentation
evaluate()
None evaluate.evaluate (DictConfig cfg = None, tf.data.Dataset eval_ds = None, Optional[str] model_path_to_evaluate = None, Optional[str] name_ds = 'test_set')
Evaluates and benchmarks a TensorFlow Lite or Keras model, and generates a Config header file if specified.
Args:
    cfg (config): The configuration file.
    eval_ds (tf.data.Dataset): The validation dataset.
    model_path_to_evaluate (str, optional): Model path to evaluate
    name_ds (str): The name of the chosen test_data to be mentioned in the prints and figures.
Returns:
    None
Definition at line 47 of file evaluate.py.
References models_mgt.ai_runner_invoke(), preprocess.apply_rescaling(), metrics.compute_ap(), postprocess.heatmaps_spe_postprocess(), metrics.multi_pose_oks_mAP(), metrics.single_pose_oks(), postprocess.spe_postprocess(), and postprocess.yolo_mpe_postprocess().