STM32N6 NPU Deployment — Politecnico di Milano: display_spe.c File Reference
display_spe.c File Reference
#include "display_spe.h"
#include "app_config.h"
#include "main.h"
#include "display_keypoints_13.h"
#include "utils.h"
#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
Functions
static void Display_keypoint (spe_pp_outBuffer_t *key, uint32_t color)
static void Display_binding (spe_pp_outBuffer_t *from, spe_pp_outBuffer_t *to, uint32_t color)
void Display_spe_InitFunctions (int clamp_point_init(int *x, int *y), void convert_length_init(float32_t wi, float32_t hi, int *wo, int *ho), void convert_point_init(float32_t xi, float32_t yi, int *xo, int *yo), void Display_binding_line_init(int x0, int y0, int x1, int y1, uint32_t color))
void Display_spe_Detection (spe_pp_outBuffer_t *detect)
Variables
static int(* clamp_point)(int *x, int *y)
static void(* convert_length)(float32_t wi, float32_t hi, int *wo, int *ho)
static void(* convert_point)(float32_t xi, float32_t yi, int *xo, int *yo)
static void(* Display_binding_line)(int x0, int y0, int x1, int y1, uint32_t color)
Detailed Description
Author
GPM Application Team
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file display_spe.c.
Function Documentation
Display_binding()
static void Display_binding (spe_pp_outBuffer_t * from, spe_pp_outBuffer_t * to, uint32_t color) static
Definition at line 64 of file display_spe.c.
References AI_POSE_PP_CONF_THRESHOLD, BINDING_WIDTH, clamp_point, convert_point, and Display_binding_line.
Referenced by Display_spe_Detection().
Display_keypoint()
static void Display_keypoint (spe_pp_outBuffer_t * key, uint32_t color) static
Definition at line 41 of file display_spe.c.
References AI_POSE_PP_CONF_THRESHOLD, CIRCLE_RADIUS, clamp_point, and convert_point.
Referenced by Display_spe_Detection().
Display_spe_Detection()
void Display_spe_Detection (spe_pp_outBuffer_t * detect)
Definition at line 111 of file display_spe.c.
References AI_POSE_PP_POSE_KEYPOINTS_NB, ARRAY_NB, bindings, Display_binding(), Display_keypoint(), and kp_color.
Referenced by Display_NetworkOutput().
Display_spe_InitFunctions()
void Display_spe_InitFunctions (int clamp_point_initint *x, int *y, void convert_length_initfloat32_t wi, float32_t hi, int *wo, int *ho, void convert_point_initfloat32_t xi, float32_t yi, int *xo, int *yo, void Display_binding_line_initint x0, int y0, int x1, int y1, uint32_t color)
Definition at line 100 of file display_spe.c.
References clamp_point, convert_length, convert_point, and Display_binding_line.
Referenced by LCD_init().
Variable Documentation
clamp_point
int(* clamp_point) (int *x, int *y) (int * x, int * y) static
Definition at line 36 of file display_spe.c.
Referenced by Display_binding(), Display_keypoint(), and Display_spe_InitFunctions().
convert_length
void(* convert_length) (float32_t wi, float32_t hi, int *wo, int *ho) (float32_t wi, float32_t hi, int * wo, int * ho) static
Definition at line 37 of file display_spe.c.
Referenced by Display_spe_InitFunctions().
convert_point
void(* convert_point) (float32_t xi, float32_t yi, int *xo, int *yo) (float32_t xi, float32_t yi, int * xo, int * yo) static
Definition at line 38 of file display_spe.c.
Referenced by Display_binding(), Display_keypoint(), and Display_spe_InitFunctions().
Display_binding_line
void(* Display_binding_line) (int x0, int y0, int x1, int y1, uint32_t color) (int x0, int y0, int x1, int y1, uint32_t color) static
Definition at line 39 of file display_spe.c.
Referenced by Display_binding(), and Display_spe_InitFunctions().