STM32N6 NPU Deployment — Politecnico di Milano: display_mpe.h File Reference
display_mpe.h File Reference
#include "mpe_yolov8_pp_if.h"
#include "mpe_pp_output_if.h"
Functions
void Display_mpe_InitFunctions (int clamp_point_init(int *x, int *y), void convert_length_init(float32_t wi, float32_t hi, int *wo, int *ho), void convert_point_init(float32_t xi, float32_t yi, int *xo, int *yo), void Display_binding_line_init(int x0, int y0, int x1, int y1, uint32_t color))
void Display_mpe_Detection (mpe_pp_outBuffer_t *detect)
Detailed Description
Author
GPM Application Team
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file display_mpe.h.
Function Documentation
Display_mpe_Detection()
void Display_mpe_Detection (mpe_pp_outBuffer_t * detect)
Definition at line 117 of file display_mpe.c.
References AI_POSE_PP_POSE_KEYPOINTS_NB, ARRAY_NB, bindings, clamp_point, colors, convert_length, convert_point, Display_binding(), Display_keypoint(), kp_color, and NUMBER_COLORS.
Referenced by Display_NetworkOutput().
Display_mpe_InitFunctions()
void Display_mpe_InitFunctions (int clamp_point_initint *x, int *y, void convert_length_initfloat32_t wi, float32_t hi, int *wo, int *ho, void convert_point_initfloat32_t xi, float32_t yi, int *xo, int *yo, void Display_binding_line_initint x0, int y0, int x1, int y1, uint32_t color)
Definition at line 106 of file display_mpe.c.
References clamp_point, convert_length, convert_point, and Display_binding_line.
Referenced by LCD_init().