STM32N6 NPU Deployment — Politecnico di Milano: parse_config Namespace Reference
parse_config Namespace Reference
Functions
None _parse_postprocessing_section (DictConfig cfg)
None _parse_dataset_section (DictConfig cfg, str hardware_type, str mode=None, DictConfig mode_groups=None)
None _parse_preprocessing_section (DictConfig cfg, str mode=None)
None _parse_data_augmentation_section (DictConfig cfg)
DefaultMunch get_config (DictConfig config_data)
Function Documentation
_parse_data_augmentation_section()
None parse_config._parse_data_augmentation_section (DictConfig cfg) private
This function checks the data augmentation section of the config file.
The attribute that introduces the section is either `data_augmentation`
or `custom_data_augmentation`. If it is `custom_data_augmentation`,
the name of the data augmentation function that is provided must be
different from `data_augmentation` as this is a reserved name.
Arguments:
    cfg (DictConfig): The entire configuration file as a DefaultMunch dictionary.
    config_dict (Dict): The entire configuration file as a regular Python dictionary.
Returns:
    None
Definition at line 137 of file parse_config.py.
Referenced by get_config().
_parse_dataset_section()
None parse_config._parse_dataset_section (DictConfig cfg, str hardware_type, str mode = None, DictConfig mode_groups = None) private
Definition at line 50 of file parse_config.py.
Referenced by get_config().
_parse_postprocessing_section()
None parse_config._parse_postprocessing_section (DictConfig cfg) private
Definition at line 39 of file parse_config.py.
Referenced by get_config().
_parse_preprocessing_section()
None parse_config._parse_preprocessing_section (DictConfig cfg, str mode = None) private
Definition at line 90 of file parse_config.py.
Referenced by get_config().
get_config()
DefaultMunch parse_config.get_config (DictConfig config_data)
Converts the configuration data, performs some checks and reformats
some sections so that they are easier to use later on.
Args:
    config_data (DictConfig): dictionary containing the entire configuration file.
Returns:
    DefaultMunch: The configuration object.
Definition at line 181 of file parse_config.py.
References _parse_data_augmentation_section(), _parse_dataset_section(), _parse_postprocessing_section(), and _parse_preprocessing_section().
Referenced by stm32ai_main.main().